ckpt: 'checkpoints/community_small/cs.pth'

data:
  name: community_small
  max_node: 20
  lifting_type: 'SCs'
  max_media_size: 20
  min_media_size: 4
  test_split: 0.2
  features: ['deg', 'eig']
  atom_channels: 21
  norm: [1.0, 1.0]
  centered: False
  latent_space: 'Laplacian'
  re_lifting: False


exp:
  plot: False

training:
  n_iters: 6000
  batch_size: 64
  continuous: True
  reduce_mean: False
  likelihood_weighting: False
  log_freq: 100
  snapshot_freq: 2000
  snapshot_sampling: False
  training_strategy: DenoisingScoreMatching
  weight_atom: 0.1
  seed: 12

OUtraining:
  n_iters: 22000
  batch_size: 32
  continuous: True
  reduce_mean: False
  likelihood_weighting: False
  log_freq: 100
  snapshot_freq: 2000
  snapshot_sampling: False
  training_strategy: DenoisingScoreMatching
  weight_atom: 0.01
  seed: 12

eval:
  batch_size: 20
  save_graph: False
  seed: 12

sampling:
  method: 'pc'
  predictor: Euler
  corrector: Langevin
  n_steps: 2
  noise_removal: True
  probability_flow: False
  atom_snr: 0.1
  bond_snr: 0.3
  scale_eps: 0.8

OUsampling:
  method: 'pc'
  predictor: Euler
  corrector: Langevin
  n_steps: 0
  noise_removal: True
  probability_flow: False
  atom_snr: None
  bond_snr: None
  scale_eps: None

sde:
  type: 'VPSDE'
  atom:
    num_scales: 300  # SDE total steps (N)
    schedule: 'linear'
    beta_min: 0.2
    beta_max: 0.9
  bond:
    num_scales: 300
    schedule: 'linear'
    beta_min: 0.2
    beta_max: 0.9

OUsde:
  type: 'OUBridge'
  atom:
    num_scales: 500
    schedule: 'linear'
    max_sigma: 1.
  bond:
    num_scales: 500
    schedule: 'linear'
    max_sigma: 1.

model:
  type: 'ScoreNet'
  ema_rate: 0.9999
  nonlinearity: 'swish'
  nf: 32
  num_gnn_layers: 6
  heads: 4
  dropout: 0.05
  bond_hid: 6
  rw_depth: 4
  edge_th: 0.5

OUmodel:
  type: 'ConScoreNet'
  ema_rate: 0.9999
  nonlinearity: 'swish'
  nf: 16
  num_gnn_layers: 5
  heads: 4
  dropout: 0.05
  bond_hid: 6
  rw_depth: 6
  edge_th: 0.5

optim:
  weight_decay: 0
  lr: 0.0001
  beta1: 0.9
  eps: 1e-08
  warmup: 1000
  grad_clip: 1.0
  optimizer: 'Adam'

OUoptim:
  weight_decay: 0
  lr: 0.001
  beta1: 0.9
  eps: 1e-08
  warmup: 1000
  grad_clip: 1.0
  optimizer: 'Adam'
